In [106]:
"""
============================================================
  CALCULATIVE FOUNDATION — Linear Algebra Project Solution
============================================================
"""

'\n============================================================\n  CALCULATIVE FOUNDATION — Linear Algebra Project Solution\n============================================================\n'

In [107]:
import numpy as np
from numpy.linalg import norm, det, inv, eig, matrix_rank
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [108]:
import numpy as np

s1 = np.array([88, 92, 85, 78, 95])
s2 = np.array([72, 68, 74, 85, 70])
s3 = np.array([95, 91, 89, 82, 98])
s4 = np.array([60, 55, 62, 70, 58])
s5 = np.array([78, 80, 75, 88, 83])
s6 = np.array([50, 48, 53, 65, 45])


## Part-A vector and matrix fundamentals

In [109]:
np.linalg.norm(s1 , 1)

np.float64(438.0)

In [110]:
np.dot(s1, s2)

np.int64(32162)

In [111]:
cos_theta = np.dot(s1, s2) / (np.linalg.norm(s1) * np.linalg.norm(s2))
angle = np.degrees(cos_theta)
angle

np.float64(56.69594011601169)

In [112]:
#select 3 subjects
np.cross([88, 92, 85], [50, 48, 53])

array([ 796, -414, -376])

In [113]:
def projection(a, b):
    return (np.dot(a, b) / np.dot(b, b)) * b


proj_s1_on_s2 = projection(s1, s2)

print("Projection of s1 onto s2:")
print(proj_s1_on_s2)

Projection of s1 onto s2:
[84.48553395 79.79189317 86.83235434 99.73986647 82.13871356]


## Part-B Matrix operations

In [114]:
scores = np.array([
s1,
s2,
s3,
s4,
s5,
s6
])


In [115]:
# Matrix Addition
scores + scores

array([[176, 184, 170, 156, 190],
       [144, 136, 148, 170, 140],
       [190, 182, 178, 164, 196],
       [120, 110, 124, 140, 116],
       [156, 160, 150, 176, 166],
       [100,  96, 106, 130,  90]])

In [116]:

np.matmul(scores, scores.T)

array([[38542, 32162, 40003, 26580, 35348, 22666],
       [32162, 27409, 33444, 22658, 29896, 19461],
       [40003, 33444, 41555, 27647, 36715, 23575],
       [26580, 22658, 27647, 18733, 24704, 16086],
       [35348, 29896, 36715, 24704, 32742, 21170],
       [22666, 19461, 23575, 16086, 21170, 13863]])

In [117]:
# transpose
scores.T

array([[88, 72, 95, 60, 78, 50],
       [92, 68, 91, 55, 80, 48],
       [85, 74, 89, 62, 75, 53],
       [78, 85, 82, 70, 88, 65],
       [95, 70, 98, 58, 83, 45]])

In [118]:
#Determinant
A = scores[:5, :5]

np.linalg.det(A)

np.float64(-95420.00000000036)

In [119]:
A = scores[:5, :5]
np.linalg.inv(A)

array([[-0.25132048,  0.69207713,  0.28650178, -0.81096206, -0.06760637],
       [ 0.03885978,  0.63315867, -0.00276672, -0.70597359, -0.08186963],
       [ 0.17938587, -0.32368476, -0.15516663,  0.48998114, -0.09152169],
       [-0.03579962, -0.01479774, -0.01039614,  0.01391742,  0.05600503],
       [ 0.07458604, -0.95248376, -0.1153427 ,  0.98505554,  0.17781388]])

## Part-C  linear transformation

 ### Explanation

Line: 1-dimensional structure

Plane: 2-dimensional surface

Hyperplane: Generalization in higher dimensions.

As dimensions increase (2D → 3D → nD), hyperplanes divide the space.

## Part-D eigenvalues and decomposition

In [120]:
cov = np.cov(scores.T)
cov

array([[285.76666667, 306.66666667, 228.8       , 106.8       ,
        352.56666667],
       [306.66666667, 341.06666667, 244.6       , 115.2       ,
        386.06666667],
       [228.8       , 244.6       , 185.2       ,  87.8       ,
        281.2       ],
       [106.8       , 115.2       ,  87.8       ,  79.6       ,
        132.6       ],
       [352.56666667, 386.06666667, 281.2       , 132.6       ,
        441.36666667]])

In [121]:
eigenvalues, eigenvectors = np.linalg.eig(cov)

print(eigenvalues)
print(eigenvectors)

[1.28417897e+03 3.83530341e+01 8.48040540e+00 4.95649643e-01
 1.49193997e+00]
[[-0.46964549 -0.07861445 -0.47539077  0.67261795  0.30796361]
 [-0.51209347 -0.13711215  0.60936918  0.29170132 -0.51238665]
 [-0.3760712   0.00252711 -0.59504753 -0.42090751 -0.57211832]
 [-0.18244546  0.97961637  0.07490835  0.02839572  0.02545292]
 [-0.58521577 -0.12395732  0.20731619 -0.53340977  0.5609377 ]]


In [122]:
U,S,Vt = np.linalg.svd(scores)

print(U)
print(S)
print(Vt)

[[-0.47210008  0.50623039  0.12796868 -0.60430244 -0.37192987  0.03103318]
 [-0.39827701 -0.39927021 -0.16931699  0.0654101  -0.26588537 -0.76047154]
 [-0.49050708  0.45682999 -0.4252682   0.3856791   0.469822   -0.01936597]
 [-0.32919831 -0.33287348 -0.32764206  0.24195586 -0.48998079  0.61225043]
 [-0.43605082 -0.12311721  0.80975557  0.33742277  0.12448568  0.09821881]
 [-0.28175859 -0.49965772 -0.10511575 -0.55623282  0.56094793  0.18933412]]
[414.66641836  28.78351121   7.1555556    3.67248679   1.60680912]
[[-0.44534765 -0.43810293 -0.43722722 -0.45971795 -0.45521759]
 [ 0.16124617  0.3075845  -0.07686168 -0.82009274  0.44825398]
 [-0.43091488  0.45764903 -0.65044066  0.30866119  0.29415124]
 [ 0.32542348 -0.66682914 -0.37366743  0.14293714  0.53794059]
 [ 0.69575647  0.24362649 -0.49012676  0.02011351 -0.46469374]]


## Part-E Dimensionality reduction

In [123]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(scores)

print(X_pca)

[[ 33.03918844  -6.27972422]
 [ -4.25544189   8.19724784]
 [ 39.80432736  -3.13621127]
 [-30.82052845  -2.31400383]
 [ 13.2387653    7.41014644]
 [-51.00631077  -3.87745497]]


In [124]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

labels = np.array([1,1,1,0,0,0])  # Above / Below average

lda = LinearDiscriminantAnalysis(n_components=1)
X_lda = lda.fit_transform(scores,labels)

print(X_lda)

[[ 1.68596794]
 [ 1.11333113]
 [ 1.95711987]
 [-0.36296909]
 [-1.3639321 ]
 [-3.02951775]]


#### Short Theoretical Answers 

Vector:
A vector is an ordered list of numbers representing magnitude and direction.

Matrix:
A matrix is a rectangular array used to represent datasets and linear transformations.

Eigenvalues:
Eigenvalues represent the amount of variance captured along eigenvectors.

SVD:
Singular Value Decomposition factors a matrix into three matrices to analyze structure.

PCA:
Principal Component Analysis reduces dimensionality while preserving maximum variance.

LDA:
Linear Discriminant Analysis projects data to maximize class separation.